# Generated by Django 6.0.6 on 2026-06-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionReference',
            fields=[
                ('fips_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(max_length=50)),
                ('county_name', models.CharField(max_length=100)),
                ('state_abbr', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Region Reference',
                'verbose_name_plural': 'Region References',
            },
        ),
        migrations.CreateModel(
            name='CrashCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('crash_date', models.DateField()),
                ('severity', models.CharField(default='minor', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crashes', to='crash_data.regionreference')),
            ],
        ),
    ]
