# Generated by Django 6.0.6 on 2026-06-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityReference',
            fields=[
                ('locality_fips', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('locality_name', models.CharField(max_length=150)),
                ('state_name', models.CharField(max_length=50)),
                ('state_abbr', models.CharField(max_length=2)),
                ('county_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Locality Reference',
                'verbose_name_plural': 'Locality References',
            },
        ),
        migrations.RemoveField(
            model_name='crashcase',
            name='region',
        ),
        migrations.RemoveField(
            model_name='crashcase',
            name='weather_conditions',
        ),
        migrations.AddField(
            model_name='crashcase',
            name='locality',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, related_name='crashes', to='crash_data.localityreference'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RegionReference',
        ),
    ]
