# Generated by Django 6.0.6 on 2026-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_data', '0002_localityreference_remove_crashcase_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localityreference',
            old_name='locality_name',
            new_name='place_name',
        ),
        migrations.RemoveField(
            model_name='localityreference',
            name='state_name',
        ),
        migrations.AddField(
            model_name='localityreference',
            name='county_fips',
            field=models.CharField(default='00000', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localityreference',
            name='county_name',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
