# Generated by Django 6.0.6 on 2026-06-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_data', '0003_rename_locality_name_localityreference_place_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localityreference',
            name='locality_fips',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
