# Generated by Django 6.0.6 on 2026-06-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_data', '0004_alter_localityreference_locality_fips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localityreference',
            options={},
        ),
        migrations.AlterField(
            model_name='localityreference',
            name='locality_fips',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='localityreference',
            name='state_abbr',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
