# Generated by Django 6.0.6 on 2026-06-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_data', '0005_alter_localityreference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localityreference',
            options={'verbose_name': 'Locality Reference', 'verbose_name_plural': 'Locality References'},
        ),
        migrations.RemoveField(
            model_name='localityreference',
            name='county_fips',
        ),
        migrations.RemoveField(
            model_name='localityreference',
            name='place_name',
        ),
        migrations.RemoveField(
            model_name='localityreference',
            name='state_abbr',
        ),
        migrations.AddField(
            model_name='localityreference',
            name='city_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='localityreference',
            name='city_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='localityreference',
            name='county_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='localityreference',
            name='st_cnty_fips_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='localityreference',
            name='state_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='localityreference',
            name='state_fips_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='localityreference',
            name='state_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='localityreference',
            name='county_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='localityreference',
            name='locality_fips',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
