# Generated by Django 6.0.6 on 2026-06-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash_data', '0006_alter_localityreference_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localityreference',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='localityreference',
            name='county_code',
        ),
        migrations.RemoveField(
            model_name='localityreference',
            name='st_cnty_fips_code',
        ),
        migrations.RemoveField(
            model_name='localityreference',
            name='state_code',
        ),
        migrations.RemoveField(
            model_name='localityreference',
            name='state_fips_code',
        ),
    ]
