# Generated by Django 6.0.6 on 2026-06-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash_data', '0007_remove_localityreference_city_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localityreference',
            old_name='locality_fips',
            new_name='jcode',
        ),
    ]
