# Generated by Django 6.0.6 on 2026-06-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_data', '0008_rename_locality_fips_localityreference_jcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localityreference',
            old_name='county_name',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='localityreference',
            old_name='state_name',
            new_name='st_name',
        ),
        migrations.RemoveField(
            model_name='localityreference',
            name='city_name',
        ),
        migrations.AddField(
            model_name='localityreference',
            name='census_place_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='localityreference',
            name='place_name_long',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='localityreference',
            name='place_name_short',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='localityreference',
            name='st',
            field=models.CharField(default='', max_length=10),
        ),
    ]
