# Generated by Django 6.0.6 on 2026-06-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_data', '0009_rename_county_name_localityreference_county_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityPopulation',
            fields=[
                ('locality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='population_data', serialize=False, to='crash_data.localityreference')),
                ('estimates_base_2020', models.IntegerField(default=0)),
                ('pop_estimate_2020', models.IntegerField(default=0)),
                ('pop_estimate_2021', models.IntegerField(default=0)),
                ('pop_estimate_2022', models.IntegerField(default=0)),
                ('pop_estimate_2023', models.IntegerField(default=0)),
                ('pop_estimate_2024', models.IntegerField(default=0)),
                ('pop_estimate_2025', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Locality Population',
                'verbose_name_plural': 'Locality Populations',
            },
        ),
    ]
