# Generated by Django 6.0.6 on 2026-06-26 18:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_data', '0010_localitypopulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localitypopulation',
            options={},
        ),
        migrations.RemoveField(
            model_name='localitypopulation',
            name='estimates_base_2020',
        ),
        migrations.RemoveField(
            model_name='localitypopulation',
            name='pop_estimate_2020',
        ),
        migrations.RemoveField(
            model_name='localitypopulation',
            name='pop_estimate_2021',
        ),
        migrations.RemoveField(
            model_name='localitypopulation',
            name='pop_estimate_2022',
        ),
        migrations.RemoveField(
            model_name='localitypopulation',
            name='pop_estimate_2023',
        ),
        migrations.RemoveField(
            model_name='localitypopulation',
            name='pop_estimate_2024',
        ),
        migrations.RemoveField(
            model_name='localitypopulation',
            name='pop_estimate_2025',
        ),
        migrations.AddField(
            model_name='localitypopulation',
            name='population_estimates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='Array of population estimates where index 0 = Year 2000, index 20 = Year 2020, etc.'),
        ),
        migrations.AlterField(
            model_name='localitypopulation',
            name='locality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crash_data.localityreference'),
        ),
    ]
